apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - control-plane-api-deployment.yaml
  - control-plane-api-service.yaml
  - control-plane-web-deployment.yaml
  - control-plane-web-service.yaml
  - control-bot-deployment.yaml